// Builds dist/jaag-core.global.js: the JAAG core bundled as a single IIFE that
// assigns `globalThis.JAAGCore` (window in a browser). Dependency free, so the
// bundle can be loaded with a plain <script> tag or inside a REvoCompute-style
// `new Function("global", "window", "document", code)` harness.
//
// The transform is intentionally small: our three core modules are pure ESM
// with single-line imports and single-line export declarations (multi-line
// initialisers/functions are preserved unchanged). It strips `import` lines,
// removes the `export ` prefix from declarations, and drops re-export blocks.
// Top-level declaration names must not collide across modules; a check rejects
// accidental duplicates.

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const shared = resolve(root, 'shared');
const distDir = resolve(root, 'dist');

const modules = [
    'jaag-schema.mjs',
    'share-payload.mjs',
    'builder.mjs'
];

function stripModule(source, label) {
    const lines = source.split('\n');
    const body = [];
    for (const line of lines) {
        if (/^\s*import\b.*;\s*$/.test(line)) continue;               // import { ... } from '...';
        if (/^\s*export\s*\{[^}]*\}\s*;?\s*$/.test(line)) continue;   // export { ... };
        body.push(line.replace(/^\s*export\s+/, ''));                  // export const|function|async function
    }
    return body.join('\n');
}

let combined = '';
const declarations = new Map();
for (const file of modules) {
    const source = readFileSync(resolve(shared, file), 'utf8');
    const stripped = stripModule(source, file);
    combined += `\n// ---- ${file} ----\n${stripped}\n`;
    for (const match of stripped.matchAll(/^(?:export\s+)?(?:async\s+)?(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm)) {
        const name = match[1];
        if (declarations.has(name)) {
            throw new Error(`Duplicate top-level declaration ${name} across bundled modules`);
        }
        declarations.set(name, file);
    }
}

const api = `{
    SCHEMA_NAME: SCHEMA_NAME,
    SCHEMA_VERSION: SCHEMA_VERSION,
    TARGETS: TARGETS,
    ADAPTERS: ADAPTERS,
    fromAlphaFold3: fromAlphaFold3,
    validateSuperset: validateSuperset,
    serialize: serialize,
    build: build,
    buildAlphaFold3Job: buildAlphaFold3Job,
    buildSuperset: buildSuperset,
    parseSeeds: parseSeeds,
    encodeSharePayload: encodeSharePayload,
    decodeSharePayload: decodeSharePayload,
    toBase64Url: toBase64Url,
    fromBase64Url: fromBase64Url,
    inflateWithDecompressionStream: inflateWithDecompressionStream,
    MAX_COMPRESSED_BYTES: MAX_COMPRESSED_BYTES,
    MAX_DECOMPRESSED_BYTES: MAX_DECOMPRESSED_BYTES
}`;

const header = `/* JAAG core — dependency-free global build. Generated by scripts/build-global.mjs. */
/* SPDX-License-Identifier: Apache-2.0 */
(function (global) {
"use strict";
var __jaagCore = (function () {
"use strict";
`;

const footer = `return ${api};
})();
global.JAAGCore = __jaagCore;
if (typeof module !== "undefined" && module && module.exports) module.exports = __jaagCore;
})(typeof window !== "undefined" ? window : (typeof globalThis !== "undefined" ? globalThis : this));
`;

const bundle = header + combined + footer;
mkdirSync(distDir, { recursive: true });
writeFileSync(resolve(distDir, 'jaag-core.global.js'), bundle);
console.log(`wrote dist/jaag-core.global.js (${bundle.length} bytes)`);
